### ISSUE TITLE
Sprint#3-T17 : Alert from bank about insufficient cash

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#10]
As the Bank should be able to let the player know about insufficient balance
Sub tasks
-----------------------------
T17.1	Design the necessary backend function
T17.2	Design a Service to handle the incoming request
T17.3	Create Test Cases
T17.4	Implement the Service
T17.5	Implement the UI
T17.6	Connect the Service to the UI

**Comment by ChathurikaDeshani** [comment]
Implemented in the frontend only, backend was already available!
