### ISSUE TITLE
Sprint#3-T18 : Bank withdraw money when buying

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#11]
As the Bank should be able to withdraw money from the player when buying shares, So that players money will reduce
Sub tasks
------------------------------------------------
T18.1	Design the necessary backend function
T18.2	Design a Service to handle the incoming request
T18.3	Create Test Cases
T18.4	Implement the Service

**Comment by marksuranjith** [comment]
Bank will withdraw money through broker
