### ISSUE TITLE
Sprint#3-T23 : Broker maintain player portfolio

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#15]
As the Broker should be able to maintain player portfolio, So that the player can get insight about their current status
Sub tasks
----------------------------------------
T23.1	Design the necessary backend function
T23.2	Design a database to store data
T23.3	Storyboard a UI to to show the portfolio info
T23.4	Design a Service to handle the incoming request
T23.5	Create Test Cases
T23.6	Implement the Service
T23.7	Implement the UI
T23.8	Connect the Service to the UI

**Comment by sampaedd** [comment]
Completed!!
