### ISSUE TITLE
Sprint#4-T11 : Player should see the current winner

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#16]
As the Player I should be able to see the current winner
Sub tasks
-------------------------------------
T11.1	Storyboard a UI to to show the winner info
T11.2	Design a Service to handle the incoming request
T11.3	Create Test Cases
T11.4	Implement the Service
T11.5	Implement the UI
T11.6	Connect the Service to the UI

**Comment by marksuranjith** [comment]
Complete
