### ISSUE TITLE
Sprint#1-T1 : Game must be fixed turn based

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#21]
As a Player, I want to play a game made up of fixed-duration turns so that I have only a limited time to decide what to buy and sell
Sub tasks
-------------------------------------
T1.1	Research how to create a fixed-duration turn based game
T1.2	Design a solution for this game
T1.3	Create Test Cases
T1.4	Implement the solution

**Comment by rhamidon** [comment]
Completed this!!!
