### ISSUE TITLE
Sprint#1-T4 : Variations between price of shares

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#22]
As a Player, I want to see variation between the prices of shares in the market.so that share prices do not change at the same rate/have the same price.
Sub tasks
-----------------------------------
T4.1	Read the Project Spec
T4.2	Design the stock market simulator
T4.3	Create Test Cases
T4.4	Implement the design

**Comment by rhamidon** [comment]
Completed this!!!
