### ISSUE TITLE
Sprint#1-T6 : See current price of shares

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#23]
As a Player, I want to be able to see the current price of shares so that they can decide what to buy/sell
Sub tasks
------------------------------------
T6.1	Storyboard a UI to capture Price Info
T6.2	Design a Service to handle the incoming request
T6.3	Create Test Cases
T6.4	Implement the Service
T6.5	Implement the UI
T6.6	Connect the Service to the UI

**Comment by rhamidon** [comment]
Completed this!!!
