### ISSUE TITLE
Sprint#1-T10 : Search valid stocks

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#24]
As a Player, I want to search the valid stock in the market so that I can buy shares what I like
Sub tasks
----------------------------------
T10.1	Storyboard a UI to show this information
T10.2	Design a Service to expose this information
T10.3	Create Test Cases
T10.4	Implement the Service
T10.5	Implement the UI
T10.6	Connect the Service to the UI

**Comment by rhamidon** [comment]
Completed this!!!
