### ISSUE TITLE
Sprint#1-T14 : Share price history

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#25]
As a Player, I want to see share price history so that I can analyze old market values and build a stratergy
Sub tasks
----------------------------
T14.1	Storyboard a UI to show this information
T14.2	Design a Service to expose this information
T14.3	Create Test Cases
T14.4	Implement the Service
T14.5	Implement the UI
T14.6	Connect the Service to the UI

**Comment by rhamidon** [comment]
Completed this!!!
