### ISSUE TITLE
Sprint#2-T5 : Buy shares

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#3]
As a player I should be able to buy shares, So that i can make money

Sub tasks:
---------------------------------------------
T3.1	Storyboard a UI to show this information
T3.2	Design a Service to expose this information
T3.3	Create Test Cases
T3.4	Implement the Service
T3.5	Implement the UI
T3.6	Connect the Service to the UI

**Comment by rhamidon** [comment]
Task 18 will implement withdraw money from bank, this is completed
