### ISSUE TITLE
Sprint#2-T12 : Seperate Bank accounts

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#4]
As a player I should be able to buy shares, So that i can make money

Sub tasks:
--------------------------------------
T12.1	Design database to store data
T12.2	Design a Service to handle incoming request
T12.3	Create Test Cases
T12.4	Implement the Service

**Comment by marksuranjith** [comment]
Implementation:
- A bankAccount is created when a player registers to the server for the first time.
- usernames are validated so no duplicate accounts will exists
- When game starts the account is updated
