### ISSUE TITLE
Sprint#2-T16 : Create player account

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#6]
As a player I should be able to create a player account for myself, So that i can maintain my own profile
Sub tasks
---------------------------------------
T16.1	Design a database to store data
T16.2	Storyboard a UI for player registration
T16.3	Design a Service to transfer this information
T16.4	Create Test Cases
T16.5	Implement the Service
T16.6	Implement the UI
T16.7	Connect the Service to the UI

**Comment by upekshaisuri** [comment]
Completed this, commit message is wrong should be Sprint#2-T16
