### ISSUE TITLE
Sprint#3-T8 : See buy/sell history

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#8]
As a player I should be able to see my buy/sell history
Sub tasks
-----------------------------------------------
T8.1	Design a database to store data
T8.2	Storyboard a UI to to show the history info
T8.3	Design a Service to handle the incoming request
T8.4	Create Test Cases
T8.5	Implement the Service
T8.6	Implement the UI
T8.7	Connect the Service to the UI

**Comment by sampaedd** [comment]
Completed this!!
