### ISSUE TITLE
Sprint#3-T9 : See current transaction

### ISSUE THREAD

**Issue by liminals** [liminals/stock-share-market#9]
As a player I should be able to see current active transaction, So that i can buy more or sell more
Sub tasks
---------------------------------------------
T9.1	Storyboard a UI to to show the current transaction
T9.2	Design a Service to handle the incoming request
T9.3	Create Test Cases
T9.4	Implement the Service
T9.5	Implement the UI
T9.6	Connect the Service to the UI

**Comment by upekshaisuri** [comment]
Completed this!
